redbubble/yak

README.md
`go get` was a bit surprised when I ran it:
```
package https:/github.com/redbubble/yak: "https://" not allowed in import path
```
Removing the `https` protocol from the package makes it happy.
=> Make the installation instructions work

cmd/list_roles.go, cmd/root.go
We can use this as a source of data for auto-completion, or, I suppose, manual completion.
=> Add aliases to --list-roles

cache/cache.go, cmd/list_roles.go, cmd/print_vars.go, cmd/shim.go
Previously, we were outputting a lot of junk to stdout. This moves a lot of it to stderr, and removes an unnecessary line from the cache library.
=> Fix yak output

Makefile, cmd/root.go
Because goreleaser sets the version string differently anyway (from
Git tags and not from the `$VERSION` variable) it's misleading to use
only the variable here, IMHO.  This makes development builds be
clearly marked as such, plus the Git commit hash they were built from.
=> Make dev builds obvious.

Makefile, README.md
Too lazy to make CloudFront and SSL and such work; compromise.
=> Serve APT from a better DNS name. Non-SSL.

cmd/root.go
We lift the version-printing thing to the beginning of `main`, because
there's no need to complain if a user has no config when running `yak
--version`.
Fixes #39
=> Showing version doesn't need any config parsing.

cmd/list_roles.go, cmd/print_vars.go, cmd/root.go, cmd/shim.go
This both makes the error handling a bit nicer internally and makes it so the cache is always exported (unless we segfault or something)
fixes #44
=> Improve error handling and always save cache 

README.md, cmd/root.go, static/completions/yak.zsh
Also add some info to the readme and helptext about how to use `yak` with flags
fixes #36  _sort of_. `yak <role> -- <command>` will still break completion, but `yak -- <role> <command>` works now. I can't find a good way to make zsh let us put the `--` in the middle of the command.
=> Explicitly tell zsh we can have a `--`

cmd/print_vars.go
=> Remove stray quotes from the env-var output

code-of-conduct.md
From https://www.contributor-covenant.org/.
Paraphrasing/plagiarising from the above site, i'd like to be overt
and explicit in our openness, welcoming all people to contribute, and
pledging in return to value them as human beings and to foster an
atmosphere of kindness, cooperation, and understanding.
Their site explains it better than i do, but i don't see why we
wouldn't adopt something like this.
=> Add Contributor Covenant.

static/completions/yak.zsh
=> Fix syntax error in `yak.zsh`

cmd/root.go
We were using XDG_DATA_HOME, but apparently there's a Folder For That.
Fixed #41
=> Use XDG_CACHE_HOME for the cache

cli/login.go
Sometimes it's not obvious which username and password the user should enter. For example, when `yak` gets called from a script, instead of the user executing it directly from bash.
=> Make credential prompts clearer

.gitignore, okta/okta.go
Corrects the VerifyPush function from trying to continue when there is an error response from the Okta API. Also extends the amount of failures that can occur before it bails out.
Fixes #65
=> Correct auth flow continuing when receiving an error response from API

cli/login.go
This makes reading lines from the terminal more portable by avoiding the assumption that lines are `\n` terminated.
This has the side effect of allowing Yak to work on Windows. >.>
=> More Portable Reading Lines

cli/login.go, cmd/root.go
This was being caused by having multiple pieces of code catch SIGINT and SIGTERM; it was possible for the exit() to happen before the terminal was reset to its original state.
=> Fix a race condition in the ^C-terminal-state-guard code

README.md, cli/login.go, cmd/list_roles.go, cmd/print_credentials.go, cmd/root.go, cmd/shim.go
I noticed the other day that there IS actually a timeout on the SAML process - it's usually quite long, but it's definitely there. This adds a configurable timeout that defaults to three minutes, which should usually be long enough for users but still shorter than Okta.
=> Add a login timeout

.goreleaser.yml
[Trello](https://trello.com/c/4qZpoKIg/3653-update-contributor-for-homebrew-repos-to-be-not-paul)
=> Change author of our releases to `delivery-engineers@redbubble.com`

cli/login.go
I tried to follow the helpful suggestion of setting up the default MFA factor in `config.toml`. It didn't work because the values were not quoted, plus I didn't know which section they need to be put in. The change I'm suggesting would make this more obvious.
=> Output valid toml snippets for config suggestion

cli/assume_role.go, cmd/print_credentials.go, cmd/shim.go
This change tests the incoming role name against a regex to determine whether or not it's an ARN for an IAM role. If not, the role name is treated as an alias. This test allows us to conclude (before making API calls!) that an incoming role name is neither a role ARN nor an alias, and hence that we can't possibly assume a role with it.
This change removes the possibility of creating aliases that look like ARNs. I think that's OK, since my imagination only gives me malicious uses cases for that.
=> Fail earlier when given a role that's neither an ARN nor an alias

cli/assume_role.go, go.mod, go.sum
Relax ARN verification rules to include other partitions, including govcloud (https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-arns.html)
Bump AWS SDK
=> Fixes #100

README.md, cmd/root.go, static/completions/yak.zsh
I have found that yak's completion breaks down in the following situation:
```ShellSession
$ yak env -- [TAB]
```
I expect it to expand possible executables, but instead, it completes filenames (which is just a Zsh fallback shining though, i believe).  A side-effect is that completions for commands i rely on also break:
```ShellSession
$ yak env -- aws [TAB] # Completes external commands, instead of aws-subcommands
$ yak env -- make [TAB] # Completes external commands, instead of make targets
```
This patch to the Zsh completion file does two main things:
* Enable the `-S` flag to `_arguments` as documented here:   https://zsh.sourceforge.io/Doc/Release/Completion-System.html#Completion-Functions.  Specifically,   "`-S` — Do not complete options after a ‘--’ appearing on the line, and …
=> Improved command completion when using '--'.

cli/assume_role.go, cli/login.go, cmd/root.go
Since `yak` is a shim, a user is almost always doing `yak foo command`, but if something goes wrong, such as forgetting the `--` in `yak fruit-role banana --peeled`, it's pretty confusing to get an error like "unknown flag --peeled", if the user knows for certain `banana` can be peeled.  This small change prefixes yak's errors, so that the user knows at a glance what failed.
=> Prefix errors with "yak:" 
